name: deploying next

on:
  push:
    branches: [ main ]

jobs:
  bulid:
   runs-on: ubuntu-22.04

   concurrency:
     group: deploy
     cancel-in-progress: true

   steps:
     - name: checkout repority
       uses: uses: actions/checkout@v7.0.0
     - name: install dependencies
       run: npm install
     - name: Build Next.js App
       run: npm run build 
     - name: Deploy App 
       run: echo "Deploying App ..."
